#!/usr/bin/env python3
"""
postprocess.py — dual-threshold filtering of patch detections by spatial isolation.

Applies a main confidence threshold (t_main), computes each patch's distance to its
k-th nearest neighbor among surviving patches, then requires a stricter threshold
(t_iso) for isolated patches (distance > D km).
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import warnings
from pathlib import Path

import geopandas as gpd
import numpy as np
from sklearn.neighbors import NearestNeighbors

KTH_NEIGHBOR_FIELD = "kth_neighbor_km"


@dataclass
class PostprocessConfig:
    """Detection-catalog conventions and the dual-threshold operating point.

    These are the parameters that define the published single-period products,
    so they live here rather than as argparse literals. The CLI defaults from
    an instance of this class.
    """

    # Dual-threshold operating point. t_main sits at the peak of the F0.5 curve;
    # isolated candidates (k-th nearest neighbour further than isolation_km)
    # must additionally clear t_iso. Website cumulatives have historically used
    # the stringent pair (0.55 / 0.8).
    t_main: float = 0.43
    t_iso: float = 0.75
    k: int = 5
    isolation_km: float = 3.0

    confidence_field: str = "confidence"

    # GeoJSON coordinate precision. Left unset it floats with the GDAL/pyogrio
    # version on whichever machine ran the job -- inference years were run on
    # different VMs, and the 2024 vintage landed at 6 decimals while every other
    # year got full float64.
    #
    # 6 decimals is ~0.11 m, about 1/100 of a pixel. What makes it right is join
    # stability, not size. Cross-year joins key on a centroid rounded to
    # centroid_decimals; at full float64 the 2018-2025 union swings by 146,485
    # locations depending on whether the analyst keys at 4, 5, 6 or 7 decimals,
    # because sub-1e-5 jitter leaves the same ground location on either side of
    # a bin edge. Writing at 6 quantizes that away: the same union varies by
    # only 228, and 2023<->2024 matching rises from 126,138 to 132,353.
    #
    # This requires a UNIFORM archive. Mixing a newly written 6-dp file against
    # a legacy full-precision one costs 4.68% of matches (7 dp -0.53%, 8 dp
    # -0.06%, 9 dp -0.01%). If you write a file that must join against
    # un-rewritten legacy data, use 9.
    coordinate_precision: int = 6

    # Join key for "same location, different period". The patch grid steps by
    # 0.00217 deg (half a patch), so 5 decimals resolves it ~217x while
    # absorbing sub-1e-5 jitter. 4 begins to collide.
    centroid_decimals: int = 5

    # buffer_deg is in decimal degrees (~1 m at equator for 1e-5)
    dissolve_buffer_deg: float = 0.00001
    dissolve_crs: str = "EPSG:4326"


_defaults = PostprocessConfig()

# Module-level aliases for the most widely imported values.
DEFAULT_CONFIDENCE_FIELD = _defaults.confidence_field
GEOJSON_COORDINATE_PRECISION = _defaults.coordinate_precision
CENTROID_DECIMALS = _defaults.centroid_decimals
DISSOLVE_CRS = _defaults.dissolve_crs


def centroid_key(gdf, decimals=CENTROID_DECIMALS,
                 write_precision=GEOJSON_COORDINATE_PRECISION):
    """Rounded patch-centre key for joining a location across periods.

    Uses bounds midpoints: patches are axis-aligned boxes, and this avoids
    shapely's centroid-in-geographic-CRS warning.

    Corners are first rounded to ``write_precision`` so the key is computed on
    the coordinates as they will be *stored*. Without that, deduplication is
    not idempotent: writing at 6 decimals quantizes away the sub-1e-5 jitter
    between records, and pairs distinct under a 5-decimal key beforehand can
    collide afterwards. Pass ``write_precision=None`` to key on the input as
    given.
    """
    b = gdf.geometry.bounds
    minx, maxx = b.minx.to_numpy(), b.maxx.to_numpy()
    miny, maxy = b.miny.to_numpy(), b.maxy.to_numpy()
    if write_precision is not None:
        minx, maxx, miny, maxy = (np.round(v, write_precision)
                                  for v in (minx, maxx, miny, maxy))
    return (np.round((minx + maxx) / 2.0, decimals),
            np.round((miny + maxy) / 2.0, decimals))


def dedupe_detections(gdf, confidence_field=DEFAULT_CONFIDENCE_FIELD,
                      decimals=CENTROID_DECIMALS, verbose=True):
    """Drop repeated patch locations, keeping the highest-confidence record.

    Inference is run as six Amazon_ACA subregions; tiles straddling a subregion
    boundary are generated by both adjacent runs and emit the same detections
    twice. About half of duplicate pairs differ slightly in confidence (median
    delta 5e-4), the subregions having been scored in separate runs, so keeping
    the maximum matches what the threshold would have done had the location
    appeared once.

    Dedupe *before* postprocessing: a duplicate sits at distance zero from its
    twin, depressing the k-th-neighbour distance used to judge isolation, so a
    pair can slip past the t_iso cutoff that should have rejected it.
    """
    if len(gdf) == 0:
        return gdf

    kx, ky = centroid_key(gdf, decimals)
    work = gdf.copy()
    work["_kx"], work["_ky"] = kx, ky
    if confidence_field in work.columns:
        work = work.sort_values(confidence_field, ascending=False, kind="mergesort")

    deduped = work.drop_duplicates(subset=["_kx", "_ky"], keep="first")
    deduped = deduped.sort_index().drop(columns=["_kx", "_ky"])

    n_dropped = len(gdf) - len(deduped)
    if verbose and n_dropped:
        print(f"Dropped {n_dropped} duplicate detections "
              f"({n_dropped / len(gdf) * 100:.2f}%); {len(deduped)} remain.")
    return deduped


def centroids_xy_m(gdf: gpd.GeoDataFrame) -> np.ndarray:
    """Patch centroids as (n, 2) coordinates in meters (projected CRS)."""
    g = gdf.copy()
    if g.crs is None:
        g = g.set_crs("EPSG:4326")
    try:
        g = g.to_crs(g.estimate_utm_crs())
    except Exception:
        g = g.to_crs("EPSG:3857")
    c = g.geometry.centroid
    return np.column_stack([c.x.to_numpy(dtype=np.float64), c.y.to_numpy(dtype=np.float64)])


def kth_neighbor_km_on_catalog(coords_m: np.ndarray, k: int) -> np.ndarray:
    """Distance (km) from each point to its k-th nearest *other* point in coords_m."""
    n = len(coords_m)
    out = np.full(n, np.nan, dtype=np.float64)
    if n <= k:
        return out
    nn = NearestNeighbors(n_neighbors=k + 1, algorithm="kd_tree")
    nn.fit(coords_m)
    dists_m, _ = nn.kneighbors(coords_m)
    out[:] = dists_m[:, k] / 1000.0
    return out


def keep_dual_threshold(
    confidence: np.ndarray,
    kth_neighbor_km: np.ndarray,
    *,
    t_main: float,
    t_iso: float,
    isolation_km: float,
) -> np.ndarray:
    """
    Return boolean mask of patches to keep.

    Positive if confidence >= t_main; isolated patches (kth_neighbor_km > isolation_km,
    or non-finite distance) also require confidence >= t_iso.
    """
    is_isolated = np.isfinite(kth_neighbor_km) & (kth_neighbor_km > isolation_km)
    if np.any(~np.isfinite(kth_neighbor_km)):
        is_isolated = is_isolated | ~np.isfinite(kth_neighbor_km)
    above_main = confidence >= t_main
    above_iso = confidence >= t_iso
    return np.where(is_isolated, above_main & above_iso, above_main)


def _fmt_param(value: float) -> str:
    return f"{value:g}"


def default_outpath(
    inpath: Path,
    *,
    t_main: float,
    k: int,
    isolation_km: float,
    t_iso: float,
) -> Path:
    """Output path: <stem>_t{t_main}_d{k}_{D}km_t-iso{t_iso}.geojson (notebook convention)."""
    stem = inpath.stem
    tag = (
        f"_t{_fmt_param(t_main)}_d{k}_{_fmt_param(isolation_km)}km"
        f"_t-iso{_fmt_param(t_iso)}"
    )
    return inpath.parent / f"{stem}{tag}.geojson"


def dissolved_outpath(patches_outpath: Path) -> Path:
    """Patch output path with -dissolved before the extension."""
    return patches_outpath.with_name(f"{patches_outpath.stem}-dissolved{patches_outpath.suffix}")


def dissolve_patches(
    gdf: gpd.GeoDataFrame,
    buffer_deg: float = 0.00001,
    conf_field: str = DEFAULT_CONFIDENCE_FIELD,
) -> gpd.GeoDataFrame:
    """
    Buffered dissolve of detection patches; aggregates confidence as mean.

    Reprojects to EPSG:4326 before buffering: ``buffer_deg`` is in decimal degrees
    (repo convention for inference GeoJSON).
    """
    gdf = gdf.copy()
    if gdf.crs is None:
        gdf = gdf.set_crs(DISSOLVE_CRS)
    else:
        gdf = gdf.to_crs(DISSOLVE_CRS)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", UserWarning)
        dissolved_geom = gdf.buffer(buffer_deg, join_style=2).union_all()
        dissolved = gpd.GeoDataFrame(geometry=[dissolved_geom], crs=gdf.crs)
        dissolved = dissolved.explode(index_parts=False).reset_index(drop=True)
        dissolved.geometry = dissolved.buffer(-buffer_deg, join_style=2)

    joined = gpd.sjoin(gdf, dissolved, how="inner", predicate="intersects")
    mean_conf = joined.groupby("index_right")[conf_field].mean()
    dissolved[conf_field] = mean_conf.reindex(dissolved.index)

    dissolved.set_crs(gdf.crs, inplace=True)
    print(f"Dissolved {len(gdf)} patches to {len(dissolved)} polygons.")
    return dissolved


def dual_threshold_filter(
    gdf: gpd.GeoDataFrame,
    *,
    t_main: float,
    t_iso: float,
    k: int,
    isolation_km: float,
    confidence_field: str = DEFAULT_CONFIDENCE_FIELD,
) -> gpd.GeoDataFrame:
    """
    Filter detections with the dual-threshold rule.

    1. Keep patches with confidence >= t_main (neighbor catalog).
    2. Compute k-th nearest-neighbor distance on that catalog.
    3. Drop isolated catalog patches (distance > isolation_km) below t_iso.
    """
    if confidence_field not in gdf.columns:
        raise KeyError(
            f"Input needs {confidence_field!r}; columns: {list(gdf.columns)}"
        )

    confidence = gdf[confidence_field].to_numpy(dtype=np.float64)
    at_main = gdf.loc[confidence >= t_main].copy()
    if len(at_main) == 0:
        out = at_main.copy()
        out[KTH_NEIGHBOR_FIELD] = np.array([], dtype=np.float64)
        return out

    coords_m = centroids_xy_m(at_main)
    at_main[KTH_NEIGHBOR_FIELD] = kth_neighbor_km_on_catalog(coords_m, k=k)

    keep = keep_dual_threshold(
        at_main[confidence_field].to_numpy(dtype=np.float64),
        at_main[KTH_NEIGHBOR_FIELD].to_numpy(dtype=np.float64),
        t_main=t_main,
        t_iso=t_iso,
        isolation_km=isolation_km,
    )
    return at_main.loc[keep].copy()


def main(args: argparse.Namespace) -> None:
    inpath = Path(args.geojson_path)
    gdf = gpd.read_file(inpath)
    if gdf.crs is None:
        gdf = gdf.set_crs("EPSG:4326")

    n_in = len(gdf)
    filtered = dual_threshold_filter(
        gdf,
        t_main=args.t_main,
        t_iso=args.t_iso,
        k=args.k,
        isolation_km=args.D,
        confidence_field=args.confidence_field,
    )

    outpath = Path(args.outpath) if args.outpath else default_outpath(
        inpath,
        t_main=args.t_main,
        k=args.k,
        isolation_km=args.D,
        t_iso=args.t_iso,
    )
    outpath.parent.mkdir(parents=True, exist_ok=True)
    filtered.to_file(outpath, driver="GeoJSON", index=False,
                     COORDINATE_PRECISION=GEOJSON_COORDINATE_PRECISION)

    n_at_main = int((gdf[args.confidence_field] >= args.t_main).sum())
    n_iso = int(
        (filtered[KTH_NEIGHBOR_FIELD] > args.D).sum()
        if len(filtered) and KTH_NEIGHBOR_FIELD in filtered.columns
        else 0
    )
    msg = (
        f"Read {n_in} patches from {inpath.name}; "
        f"{n_at_main} at t_main={args.t_main:g}; "
        f"wrote {len(filtered)} ({n_iso} isolated with d > {args.D:g} km) "
        f"to {outpath}"
    )
    if args.dissolve:
        dissolved_path = dissolved_outpath(outpath)
        dissolved = dissolve_patches(
            filtered, conf_field=args.confidence_field
        )
        dissolved.to_file(dissolved_path, driver="GeoJSON", index=False,
                          COORDINATE_PRECISION=GEOJSON_COORDINATE_PRECISION)
        msg += f"; dissolved -> {dissolved_path}"
    print(msg)


if __name__ == "__main__":
    defaults = PostprocessConfig()

    parser = argparse.ArgumentParser(
        description=(
            "Dual-threshold post-processing: filter patch detections by confidence "
            "and spatial isolation (k-th nearest neighbor distance)."
        ),
    )
    parser.add_argument(
        "geojson_path",
        help="Input GeoJSON with patch detections and a confidence field.",
    )
    parser.add_argument(
        "--outpath",
        default=None,
        help=(
            "Output GeoJSON path. Default: input stem + "
            "_t{t_main}_d{k}_{D}km_t{t_iso}.geojson"
        ),
    )
    parser.add_argument(
        "--t-main",
        dest="t_main",
        type=float,
        default=defaults.t_main,
        help=f"Main confidence threshold (default: {defaults.t_main:g}).",
    )
    parser.add_argument(
        "--t-iso",
        dest="t_iso",
        type=float,
        default=defaults.t_iso,
        help=f"Stricter threshold for isolated patches (default: {defaults.t_iso:g}).",
    )
    parser.add_argument(
        "-k",
        "--k",
        type=int,
        default=defaults.k,
        help=f"Neighbor rank for isolation distance, e.g. 5 = 5th NN (default: {defaults.k}).",
    )
    parser.add_argument(
        "-D",
        "--D",
        type=float,
        default=defaults.isolation_km,
        help="Isolation cutoff in km; patches with k-th NN distance > D use t_iso.",
    )
    parser.add_argument(
        "--confidence-field",
        default=defaults.confidence_field,
        help=f"Confidence column name (default: {defaults.confidence_field}).",
    )
    parser.add_argument(
        "--dissolve",
        action="store_true",
        help=(
            "Also write a buffered-dissolve polygon layer as "
            "<patch-outstem>-dissolved.geojson"
        ),
    )

    main(parser.parse_args())
