"""Concatenate detection FeatureCollections, deduplicating shared locations.

Inference over the Amazon is split across the six Amazon_ACA subregions. Tiles
straddling a subregion boundary are generated by *both* adjacent runs, and chips
are cut across the whole tile, so those tiles emit the same detections twice.
Plain concatenation therefore double-counts a band one tile wide along every
seam: measured on 2023, 1,053 locations appear in more than one subregion file
while only 2 duplicates exist within a single file, and 99.9% of them sit within
0.05 deg (one tile width) of a seam.

Deduplication is not cosmetic. A duplicate sits at distance zero from its twin,
which depresses the k-th-nearest-neighbour distance that postprocess.py uses to
decide isolation -- so an undeduplicated pair can slip past the stricter t_iso
threshold that should have rejected it. Dedupe before postprocessing, not after.
"""

import argparse
from pathlib import Path

import geopandas as gpd
import numpy as np

DEFAULT_CONFIDENCE_FIELD = "confidence"

# Detections are axis-aligned patches on a stable grid whose step is 0.00217 deg
# (half a patch). 5 decimals resolves that ~217x while absorbing the sub-1e-5
# jitter that makes exact coordinate matching unreliable across runs and
# machines. See docs/design/persistence-planning.md.
CENTROID_DECIMALS = 5


def centroid_key(gdf, decimals=CENTROID_DECIMALS):
    """Rounded patch-centre key. Uses bounds midpoints: patches are boxes, and
    this avoids shapely's centroid-in-geographic-CRS warning."""
    b = gdf.geometry.bounds
    return (
        np.round((b.minx.to_numpy() + b.maxx.to_numpy()) / 2.0, decimals),
        np.round((b.miny.to_numpy() + b.maxy.to_numpy()) / 2.0, decimals),
    )


def dedupe_detections(gdf, confidence_field=DEFAULT_CONFIDENCE_FIELD,
                      decimals=CENTROID_DECIMALS, verbose=True):
    """Drop repeated patch locations, keeping the highest-confidence record.

    Duplicate pairs are not always identical: about half differ slightly in
    confidence (median delta 5e-4), the two subregions having been scored in
    separate runs. Keeping the maximum matches what the postprocess threshold
    would have done had the location appeared once.
    """
    if len(gdf) == 0:
        return gdf

    kx, ky = centroid_key(gdf, decimals)
    work = gdf.copy()
    work["_kx"], work["_ky"] = kx, ky

    if confidence_field in work.columns:
        work = work.sort_values(confidence_field, ascending=False, kind="mergesort")

    deduped = work.drop_duplicates(subset=["_kx", "_ky"], keep="first")
    deduped = deduped.sort_index().drop(columns=["_kx", "_ky"])

    n_dropped = len(gdf) - len(deduped)
    if verbose and n_dropped:
        print(f"Dropped {n_dropped} duplicate detections "
              f"({n_dropped / len(gdf) * 100:.2f}%); {len(deduped)} remain.")
    return deduped


def concatenate(paths, outpath, dedupe=True):
    """Concatenate FeatureCollections, deduplicating shared locations."""
    if not paths:
        raise ValueError("At least one input path is required.")

    gdf = gpd.pd.concat([gpd.read_file(p) for p in paths], ignore_index=True)
    if dedupe:
        gdf = dedupe_detections(gdf)

    Path(outpath).parent.mkdir(parents=True, exist_ok=True)
    # Pinned so precision does not float with the GDAL/pyogrio version; see
    # core/postprocess.py and docs/design/persistence-planning.md.
    gdf.to_file(outpath, driver="GeoJSON", index=False,
                COORDINATE_PRECISION=6)
    print(f"Wrote {len(gdf)} detections to {outpath}")


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description=(
            "Concatenate model detection GeoJSONs, dropping locations that "
            "repeat because a tile straddled a subregion boundary. Passing a "
            "single path deduplicates that file on its own."
        ))
    parser.add_argument(
        "paths", nargs="*",
        help="Names of files with model detections to concatenate.",
        default=[])
    parser.add_argument(
        "--outpath", type=str,
        help="Path to write concatenated detections",
        default='./combined_detections.geojson')
    parser.add_argument(
        "--no-dedupe", dest="dedupe", action="store_false",
        help="Keep duplicate patch locations (not recommended; see module docstring).")

    args = parser.parse_args()
    concatenate(**vars(args))
