"""Concatenate detection FeatureCollections, deduplicating shared locations.

Inference over the Amazon is run as the six Amazon_ACA subregions rather than a
single job. Tiles straddling a subregion boundary are generated by *both*
adjacent runs, and chips are cut across the whole tile, so those tiles emit the
same detections twice. Plain concatenation double-counts a band one tile wide
along every seam.

The deduplication logic lives in ``core/postprocess.py`` alongside the rest of
the detection-catalog operations; this is the CLI over it.
"""

import argparse
import sys
from pathlib import Path

import geopandas as gpd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "core"))
from postprocess import PostprocessConfig, dedupe_detections  # noqa: E402


def concatenate(paths, outpath, dedupe=True):
    """Concatenate FeatureCollections, deduplicating shared locations."""
    if not paths:
        raise ValueError("At least one input path is required.")

    config = PostprocessConfig()
    gdf = gpd.pd.concat([gpd.read_file(p) for p in paths], ignore_index=True)
    if dedupe:
        gdf = dedupe_detections(gdf, confidence_field=config.confidence_field,
                                decimals=config.centroid_decimals)

    Path(outpath).parent.mkdir(parents=True, exist_ok=True)
    gdf.to_file(outpath, driver="GeoJSON", index=False,
                COORDINATE_PRECISION=config.coordinate_precision)
    print(f"Wrote {len(gdf)} detections to {outpath}")


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description=(
            "Concatenate model detection GeoJSONs, dropping locations that "
            "repeat because a tile straddled a subregion boundary. Passing a "
            "single path deduplicates that file on its own."
        ))
    parser.add_argument(
        "paths", nargs="*",
        help="Names of files with model detections to concatenate.",
        default=[])
    parser.add_argument(
        "--outpath", type=str,
        help="Path to write concatenated detections",
        default='./combined_detections.geojson')
    parser.add_argument(
        "--no-dedupe", dest="dedupe", action="store_false",
        help="Keep duplicate patch locations (not recommended; see module docstring).")

    args = parser.parse_args()
    concatenate(**vars(args))
